name: 'Tests'

on: [push]

jobs:
  Python-module-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["pypy3.10", "3.10", "3.11", "3.12"]
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
      - run: pip install -r test/pytest/requirements.txt
      - run: pip install -r znvs/requirements.txt
      - run: bash ${{ github.workspace }}/script/run_pytest.sh
